spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springsecurity?lob=non_contextual_creation=true
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
